### ISSUE TITLE
panic: frame bounds or size not consistent, this should not happen

### ISSUE THREAD

**Issue by astro** [jo-m/trainbot#2]
Just trying this out...

`trainbot --log-pretty --input /dev/video0 --camera-format-fourcc=MJPG -X 600 -Y 340 -W 400 -H 300 --px-per-m=40`

```
[...]
12:20AM INF github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:278 > start of new sequence
12:20AM INF github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:191 > end of sequence, trying to stitch
12:20AM INF github.com/jo-m/trainbot/internal/pkg/stitch/stitch.go:194 > fitAndStitch() dx=[86,88,1,44,54,52,50,53,42,42,1,0,59,46,36,33,30,32,38,47,46,37,1,42,44,41,44,48,47,56,72,35,0,45,45,51,52,0,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] len(frames)=57
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:194 > unable to fit and stitch sequence error="was not able to fit the sequence: RANSAC unsuccessful"
12:20AM INF github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:278 > start of new sequence
12:20AM INF github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:191 > end of sequence, trying to stitch
12:20AM INF github.com/jo-m/trainbot/internal/pkg/stitch/stitch.go:194 > fitAndStitch() dx=[-71,-84,-114,-99,-67,-59,-59,-56,-54,-53,-37,-29,-41,-41,-36,-42,-44,-46,-45,-44,-42,-27,-29,-28,-30,-38,-36,-39,-44,-48,-13,-53,-52,-47,-48,-27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] len(frames)=55
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:194 > unable to fit and stitch sequence error="was not able to fit the sequence: RANSAC unsuccessful"
12:20AM INF github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:278 > start of new sequence
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.100236147 maxDx*3=537
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.100061264 maxDx*3=534
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.099759827 maxDx*3=534
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.100673147 maxDx*3=537
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.099532631 maxDx*3=531
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.099793561 maxDx*3=534
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.100027111 maxDx*3=534
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.09994344 maxDx*3=534
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.099959504 maxDx*3=534
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.100374644 maxDx*3=537
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.099873669 maxDx*3=534
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.099777077 maxDx*3=534
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.100093671 maxDx*3=534
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.099918577 maxDx*3=534
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.099952101 maxDx*3=534
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.10011141 maxDx*3=534
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.10016414 maxDx*3=537
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.099359983 maxDx*3=531
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.100380231 maxDx*3=537
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.099905447 maxDx*3=534
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.100090387 maxDx*3=534
12:20AM ERR github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:238 > image is not wide enough to resolve the given max speed dx=400 framePeriodS=0.100052674 maxDx*3=534
12:20AM INF github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:191 > end of sequence, trying to stitch
12:20AM INF github.com/jo-m/trainbot/internal/pkg/stitch/stitch.go:194 > fitAndStitch() dx=[47,55,66,54,1,1,46,55,51,51,62,60,53,39,39,0,51,50,48,46,44,41,44,52,43,44,0,0,1,-6,4,-1,0,1,-1,0,0,0,14,11,7,5,3,1,0,0,0] len(frames)=47
12:20AM INF github.com/jo-m/trainbot/internal/pkg/stitch/stitch.go:46 > stitch() dx=[64,63,58,62,60,56,59,57,53,55,55,50,53,52,48,50,49,45,47,46,42,44,43,40,42,39,249,6,5,5,3,3,2,0,0,-1,-2,-3,-4,-5,-6,-7,-8,-8] len(frames)=44
12:20AM PNC github.com/jo-m/trainbot/internal/pkg/stitch/stitch.go:60 > frame bounds or size not consistent, this should not happen
12:20AM INF github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:187 > nothing to assemble
panic: frame bounds or size not consistent, this should not happen

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0x1009f9a?, 0x0?})
	github.com/rs/zerolog@v1.29.1/log.go:376 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc002436c00, {0x1009f9a, 0x3b})
	github.com/rs/zerolog@v1.29.1/event.go:156 +0x2a5
github.com/rs/zerolog.(*Event).Msg(...)
	github.com/rs/zerolog@v1.29.1/event.go:108
github.com/jo-m/trainbot/internal/pkg/stitch.stitch({0xc00048b400, 0x2c, 0x1da0480?}, {0xc000148580, 0x2c, 0x2c})
	github.com/jo-m/trainbot/internal/pkg/stitch/stitch.go:60 +0x39c
github.com/jo-m/trainbot/internal/pkg/stitch.fitAndStitch({0xc0002027c8, {0xc00048b400, 0x2c, 0x40}, {0xc000038800, 0x2c, 0x40}, {0xc00015e000, 0x2c, 0x40}}, ...)
	github.com/jo-m/trainbot/internal/pkg/stitch/stitch.go:232 +0x585
github.com/jo-m/trainbot/internal/pkg/stitch.(*AutoStitcher).TryStitchAndReset(0xc0000cbac0)
	github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:192 +0x19e
github.com/jo-m/trainbot/internal/pkg/stitch.(*AutoStitcher).Frame(0xc0000cbac0, {0x1316250, 0xc000054d00}, {0x7ffedb62ce1c?, 0xb?, 0x1da0480?})
	github.com/jo-m/trainbot/internal/pkg/stitch/auto.go:265 +0x852
main.detectTrainsForever({{0x1, {0xee686d, 0x4}}, {0x7ffedb62ce1c, 0xb}, {0x7ffedb62ce3f, 0x4}, 0x780, 0x438, 0x258, ...}, ...)
	github.com/jo-m/trainbot/cmd/trainbot/main.go:165 +0x606
main.main()
	github.com/jo-m/trainbot/cmd/trainbot/main.go:350 +0x7c5
```

**Comment by jo-m** [comment]
In the log you posted, you can see that the sequence of dx (pixel distances between frames) looks like this:

```
12:20AM INF github.com/jo-m/trainbot/internal/pkg/stitch/stitch.go:46 > stitch() dx=[64,63,58,62,60,56,59,57,53,55,55,50,53,52,48,50,49,45,47,46,42,44,43,40,42,39,249,6,5,5,3,3,2,0,0,-1,-2,-3,-4,-5,-6,-7,-8,-8]
```

which means we'd have to stitch a picture where the train starts appearing in the frame moving in one direction, and then turns around. This contradicts point 7 listed here: https://github.com/jo-m/trainbot/blob/master/README.md#assumptions-and-notes-on-computer-vision

I am not sure how it came to this:
- did you wave back and forth your finger in front of the camera?
- did you have two trains crossing so it appeared to trainbot that one train was turning around

Could also of course be a bug in my smoothing method, although the input data of `[47,55,66,54,1,1,46,55,51,51,62,60,53,39,39,0,51,50,48,46,44,41,44,52,43,44,0,0,1,-6,4,-1,0,1,-1,0,0,0,14,11,7,5,3,1,0,0,0]` looks pretty bad.

Still, we could prob. just print an error instead of panicing.

**Comment by astro** [comment]
I was shakily holding a phone with a train video in front of my webcam.

If the crash is going to happen when two trains cross, that's a problem.

**Comment by jo-m** [comment]
So, while train crossings are not really supported (see readme) and produce weird results (e.g. https://trains.jo-m.ch/#/trains/3447, one train stitched in reverse), they should not crash the system.
I would assume the problem is more with the shaky phone, we require a stable image.

I suggest that you try to feed the video file into the program directly, see Makefile for sample invocation.

**Comment by jo-m** [comment]
If you send me the video, I can also try it myself.

**Comment by astro** [comment]
https://www.youtube.com/watch?v=TJoB2bHbxQg

**Comment by jo-m** [comment]
With the last commit b24e9b3da4f4a1dd639bea9a42c6e52ffe596df5, and some tuning of parameters, it actually works (to some extent, it still gets chopped up due to all the stuff in the way) on the 360p downloaded version:


```
run_videofile:
	go build -o build/trainbot ./cmd/trainbot/
	./build/trainbot \
		--log-pretty \
		--log-level=debug \
		--min-speed-kph=5 \
		--max-speed-kph=50 \
		--px-per-m=100 \
		--min-len-m=1 \
		\
		--input="Vintage steam train passes through newly upgraded crossing.mp4" \
		-X 130 -Y 80 -W 300 -H 200
```
![train_20191201_105640 482_Z](https://user-images.githubusercontent.com/2587503/236609232-af0e7f7a-4bb7-4434-bd57-e0e48685e5d1.jpg)

![train_20191201_105644 517_Z](https://user-images.githubusercontent.com/2587503/236609233-7b75cc51-30fa-4e83-892e-1a9c1d07c4b4.jpg)

![train_20191201_105638 034_Z](https://user-images.githubusercontent.com/2587503/236609230-ab80c3e6-f6dd-495e-a88a-210d5e5d0f67.jpg)

BTW, when I write train crossing, I don't mean a road/rail crossing, but rather two trains crossing from two opposite directions.
